### PR TITLE
[FEATURE] Add Article and Footer components

### PR DESCRIPTION
**Pull request by V3ntus**
Closes # 

## 📑 Description
Adds a simple Article and Footer component

**Article:**
Props API:
| Key | Description |
| ------------ | ---------- |
| `backgroundColor` | Set the background color of the article |
| `articleHeading` | The heading text of the article |
| `articleAuthor` | The author text of the article |
| `articleBody` | The body text of the article |

**Footer:**
Order is defined by the user. In this example, author will be rendered before copyright:
```py
Footer.item(
	{
		"footerAuthor": "V3ntus",
		"footerCopyright": "Joe"
	}
)
```
| Key | Description |
| ------------ | ---------- |
| `backgroundColor` | Set the background color of the footer |
| `footerAuthor` | The author text of the footer |
| `footerEmail` | The email text of the footer |
| `footerCopyright` | The copyright text of the footer |
| `footerDelimiter` | The delimiter that separates each subitem in the footer |

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [*] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by Sas2k** [comment]
Hey @V3ntus, Thanks for the Footer and Article Components!
the props are used like this actually,
```
<Footer footerAuthor="Sas2k" footerCopyright="2022 @ Lemon-CLI"/>
```
Since, the code any everything is great I will accept your PR.
Great Job!.

**Comment by Sas2k** [comment]
Also in the `footer.py` you had some F-string issues, but don't worry I fixed them.

**Comment by V3ntus** [comment]
Ah sorry for the mix up. Thank you!

**Comment by Sas2k** [comment]
No problem

**Pull request merged**
